name: Frontend linting

on:
  push:
    branches: [ main ]
    paths:
      - "src/frontend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "src/frontend/**"

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Run prettier on frontend
        run: |
          cd ./src/frontend
          npm install -g prettier
          npx prettier --check .
